In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# To run numpy library use import function

In [1]:
import numpy as np
myarr=np.array([1,2,3])
myarr

array([1, 2, 3])

# Shape of array 

In [3]:
myarr.shape

(3,)

# Datatype of array

In [4]:
myarr.dtype

dtype('int32')

# Array creation : Conversion from python structures

In [5]:
import numpy as np
listarray=np.array([[1,2,3],[5,8,5],[4,6,7]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [4, 6, 7]])

# Size of array

In [6]:
listarray.size

9

# Intrinsic numpy creation objects

In [7]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Arange pf array

In [8]:
rng = np.arange(14)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [9]:
# this function use for equal space in array
lspace =np.linspace(1,9,5)
lspace

array([1., 3., 5., 7., 9.])

In [10]:
#empty function use for empty array and output given anything 
emp =np.empty((4,6))
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
#empty_like function uses when replace another array 
emp_like=np.empty_like(lspace)
emp_like

array([1., 3., 5., 7., 9.])

In [12]:
#ide function use for identity and that's give 12 x 12 matrix
ide=np.identity(12)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
arr =np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [14]:
arr =arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [15]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [16]:
x=np.array([[1,2,3],[4,5,6,],[8,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [8, 5, 6]])

In [17]:
ar=np.array(x)

In [18]:
#axis(0) shows horizontal line
#axis(1) shows verticle line
ar.sum(axis=0)

array([13, 12, 15])

In [19]:
ar.sum(axis=1)

array([ 6, 15, 19])

In [20]:
#in this array T means transform which is transform array
ar.T

array([[1, 4, 8],
       [2, 5, 5],
       [3, 6, 6]])

In [21]:
ar.flat

In [22]:
for item in ar.flat:
 print(item)

1
2
3
4
5
6
8
5
6


In [23]:
#ndim means number of dimantions
ar.ndim

2

In [24]:
#number of bytes
ar.nbytes

36

In [25]:
# maximum 
one=np.array([1,3,4,5,5])
one.argmax()

3

In [26]:
#minimum
one.argmin()

0

In [27]:
#sorting of array
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [28]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [8, 5, 6]])

In [29]:
ar.argmin()

0

In [30]:
ar.argmax()

6

In [31]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [32]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [33]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [34]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [35]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 8, 5, 6])

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [8, 5, 6]])

In [37]:
ar2=np.array([1,2,3])
ar2

array([1, 2, 3])

In [38]:
ar + ar2

array([[2, 4, 6],
       [5, 7, 9],
       [9, 7, 9]])

In [39]:
ar * ar2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 8, 10, 18]])

In [40]:
ar - ar2

array([[0, 0, 0],
       [3, 3, 3],
       [7, 3, 3]])

In [41]:
ar / ar2

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [8. , 2.5, 2. ]])

In [42]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.82842712, 2.23606798, 2.44948974]])

In [43]:
ar.sum()

40

In [44]:
ar.max()

8

In [45]:
ar.min()

1

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [8, 5, 6]])

In [47]:
#to show greaterthan 5 number value
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 2], dtype=int64))

In [48]:
#to show type 
type(np.where(ar>5))

tuple

In [49]:
np.count_nonzero(ar)

9

In [50]:
ar[1,2]=0

In [51]:
#show non zeros inarra
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [52]:
import sys

In [53]:
py_ar=[1,2,3,4]

In [54]:
np_ar=np.array(py_ar)

In [55]:
sys.getsizeof(1)*len(py_ar)

112

In [56]:
np_ar.itemsize*np_ar.size

16

In [57]:
np_ar.tolist()

[1, 2, 3, 4]